### ISSUE TITLE
AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks'

### ISSUE THREAD

**Issue by webdevbrian** [wmcnally/deep-darts#5]
Getting an error running the mentioned train command in the `README.md` file. Command: `python train.py --cfg deepdarts_d1`

```
(deep-darts) C:\Users\phroz\development\deep-darts>python train.py --cfg deepdarts_d1
Running on CPU
Number of accelerators:  1
WARNING:tensorflow:Skipping loading of weights for layer PANetTiny due to mismatch in shape ((1, 1, 512, 30) vs (1, 1, 512, 255)).
WARNING:tensorflow:Skipping loading of weights for layer PANetTiny due to mismatch in shape ((30,) vs (255,)).
WARNING:tensorflow:Skipping loading of weights for layer PANetTiny due to mismatch in shape ((1, 1, 256, 30) vs (1, 1, 256, 255)).
WARNING:tensorflow:Skipping loading of weights for layer PANetTiny due to mismatch in shape ((30,) vs (255,)).
Traceback (most recent call last):
  File "train.py", line 152, in <module>
    yolo = train(cfg, strategy)
  File "train.py", line 99, in train
    batch_size=cfg.train.batch_size * strategy.num_replicas_in_sync)
  File "C:\Users\phroz\development\deep-darts\dataloader.py", line 258, in load_tfds
    data = get_splits(cfg.data.labels_path, cfg.data.dataset, split)
  File "C:\Users\phroz\development\deep-darts\dataloader.py", line 34, in get_splits
    df = pd.read_pickle(path)
  File "C:\Users\phroz\.conda\envs\deep-darts\lib\site-packages\pandas\io\pickle.py", line 187, in read_pickle
    return pc.load(f, encoding=None)
  File "C:\Users\phroz\.conda\envs\deep-darts\lib\site-packages\pandas\compat\pickle_compat.py", line 249, in load
    return up.load()
  File "C:\Users\phroz\.conda\envs\deep-darts\lib\pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "C:\Users\phroz\.conda\envs\deep-darts\lib\pickle.py", line 1382, in load_stack_global
    self.append(self.find_class(module, name))
  File "C:\Users\phroz\.conda\envs\deep-darts\lib\site-packages\pandas\compat\pickle_compat.py", line 189, in find_class
    return super().find_class(module, name)
  File "C:\Users\phroz\.conda\envs\deep-darts\lib\pickle.py", line 1425, in find_class
    return _getattribute(sys.modules[module], name)[0]
  File "C:\Users\phroz\.conda\envs\deep-darts\lib\pickle.py", line 299, in _getattribute
    .format(name, obj)) from None
AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from 'C:\\Users\\phroz\\.conda\\envs\\deep-darts\\lib\\site-packages\\pandas\\core\\internals\\blocks.py'>
```

**Comment by Saturi92** [comment]
@webdevbrian  It seems you were also playing around here.
I also started yesterday after I found this very interesting project.
However, I also run into issues trying to train/test my setup.
Were you eventually successfull?
